# Cloudflare Worker configuration for static site deployment
name = "helllo-ai-staging-homepage"
compatibility_date = "2025-08-14"
main = "src/worker.ts"

# Static assets configuration
[assets]
binding = "ASSETS"
directory = "./dist"
